### ISSUE TITLE
images

### ISSUE THREAD

**Issue by SMITA-ME** [OWASP/www-chapter-gujarat-technological-university#2]
![logo](https://user-images.githubusercontent.com/89657173/136672956-dc3689fb-106d-4803-9768-32130ab2f33f.png)

**Comment by SMITA-ME** [comment]
![logo](https://user-images.githubusercontent.com/89657173/153816298-56c9c64c-2dfa-4501-bbea-84e16d9f084b.png)

**Comment by GSET-SLC-OWASP** [comment]
![GTU_Logo](https://github.com/user-attachments/assets/0f01163e-41a9-4fa4-80e4-4fcd44908696)
